export const converterCategories = [
  {
    group: "Core Daily Converters",
    items: [
      {
        id: 1,
        name: "Length / Distance",
        type: "unit",
        units: ["m", "cm", "mm", "km", "in", "ft", "yd", "mi"],
        base: "m",
      },
      {
        id: 2,
        name: "Weight / Mass",
        type: "unit",
        units: ["kg", "g", "mg", "t", "lb", "oz"],
        base: "kg",
      },
      {
        id: 3,
        name: "Temperature",
        type: "unit",
        units: ["°C", "°F", "K"],
        base: "K",
      },
      {
        id: 4,
        name: "Area",
        type: "unit",
        units: ["m²", "cm²", "km²", "ha", "ac", "ft²", "in²"],
        base: "m²",
      },
      {
        id: 5,
        name: "Volume",
        type: "unit",
        units: ["L", "mL", "m³", "gal", "qt", "pt", "fl oz"],
        base: "L",
      },
      {
        id: 6,
        name: "Speed",
        type: "unit",
        units: ["m/s", "km/h", "mph", "kn", "ft/s"],
        base: "m/s",
      },
      {
        id: 7,
        name: "Time",
        type: "unit",
        units: ["s", "ms", "min", "h", "day", "week", "year"],
        base: "s",
      },
      {
        id: 8,
        name: "Pressure",
        type: "unit",
        units: ["Pa", "kPa", "bar", "atm", "psi", "mmHg"],
        base: "Pa",
      },
      {
        id: 9,
        name: "Energy / Heat",
        type: "unit",
        units: ["J", "kJ", "cal", "kcal", "Wh", "kWh", "BTU"],
        base: "J",
      },
      {
        id: 10,
        name: "Power",
        type: "unit",
        units: ["W", "kW", "MW", "hp", "BTU/h"],
        base: "W",
      },
      {
        id: 11,
        name: "Force",
        type: "unit",
        units: ["N", "kN", "lbf", "dyn"],
        base: "N",
      },
      {
        id: 12,
        name: "Angle",
        type: "unit",
        units: ["deg", "rad", "grad", "rev"],
        base: "rad",
      },
      {
        id: 13,
        name: "Density",
        type: "unit",
        units: ["kg/m³", "g/cm³", "lb/ft³"],
        base: "kg/m³",
      },
      {
        id: 14,
        name: "Torque",
        type: "unit",
        units: ["Nm", "lb-ft", "lb-in"],
        base: "Nm",
      },
      {
        id: 15,
        name: "Acceleration",
        type: "unit",
        units: ["m/s²", "g", "ft/s²"],
        base: "m/s²",
      },
    ],
  },
  {
    group: "Digital & Computer Converters",
    items: [
      {
        id: 16,
        name: "Data Storage",
        type: "unit",
        units: ["B", "KB", "MB", "GB", "TB", "PB"],
        base: "B",
      },
      {
        id: 17,
        name: "Data Transfer Rate",
        type: "unit",
        units: ["bps", "Kbps", "Mbps", "Gbps", "MB/s"],
        base: "bps",
      },
      {
        id: 18,
        name: "Frequency",
        type: "unit",
        units: ["Hz", "kHz", "MHz", "GHz"],
        base: "Hz",
      },
      {
        id: 19,
        name: "Bit/Byte Converter",
        type: "unit",
        units: ["bit", "byte"],
        base: "bit",
      },
      {
        id: 20,
        name: "File Size Calculator",
        type: "calculator",
        inputs: [
          { name: "duration", unit: "s" },
          { name: "bitrate", unit: "kbps" },
        ],
      },
    ],
  },
  {
    group: "Financial & Business Converters",
    items: [
      {
        id: 21,
        name: "Currency Converter",
        type: "unit",
        units: ["USD", "EUR", "GBP", "JPY", "PKR"],
        base: "USD",
        api: true,
      },
      {
        id: 22,
        name: "Loan / EMI Calculator",
        type: "calculator",
        inputs: [
          { name: "principal", unit: "$" },
          { name: "rate", unit: "%" },
          { name: "time", unit: "years" },
        ],
      },
      {
        id: 23,
        name: "Interest Rate Calculator",
        type: "calculator",
        inputs: [
          { name: "principal", unit: "$" },
          { name: "amount", unit: "$" },
          { name: "time", unit: "years" },
        ],
      },
      {
        id: 24,
        name: "Discount Calculator",
        type: "calculator",
        inputs: [
          { name: "price", unit: "$" },
          { name: "discount", unit: "%" },
        ],
      },
      {
        id: 25,
        name: "Sales Tax / VAT Calculator",
        type: "calculator",
        inputs: [
          { name: "price", unit: "$" },
          { name: "tax", unit: "%" },
        ],
      },
      {
        id: 26,
        name: "Investment Return Calculator (ROI)",
        type: "calculator",
        inputs: [
          { name: "investment", unit: "$" },
          { name: "return", unit: "$" },
        ],
      },
    ],
  },
  {
    group: "Engineering & Science Converters",
    items: [
      {
        id: 27,
        name: "Electric Voltage",
        type: "unit",
        units: ["V", "mV", "kV"],
        base: "V",
      },
      {
        id: 28,
        name: "Electric Current",
        type: "unit",
        units: ["A", "mA", "kA"],
        base: "A",
      },
      {
        id: 29,
        name: "Electric Resistance",
        type: "unit",
        units: ["Ω", "kΩ", "MΩ"],
        base: "Ω",
      },
      {
        id: 30,
        name: "Electric Power",
        type: "unit",
        units: ["W", "kW", "MW"],
        base: "W",
      },
      {
        id: 31,
        name: "Capacitance",
        type: "unit",
        units: ["F", "μF", "pF"],
        base: "F",
      },
      {
        id: 32,
        name: "Inductance",
        type: "unit",
        units: ["H", "mH", "μH"],
        base: "H",
      },
      {
        id: 33,
        name: "Electric Charge",
        type: "unit",
        units: ["C", "mAh"],
        base: "C",
      },
      {
        id: 34,
        name: "Magnetic Field Strength",
        type: "unit",
        units: ["T", "G"],
        base: "T",
      },
      {
        id: 35,
        name: "Illuminance",
        type: "unit",
        units: ["lx", "lm"],
        base: "lx",
      },
      {
        id: 36,
        name: "Specific Heat Capacity",
        type: "unit",
        units: ["J/kg·K", "cal/g·°C"],
        base: "J/kg·K",
      },
      {
        id: 37,
        name: "Fuel Efficiency",
        type: "unit",
        units: ["km/l", "mpg"],
        base: "km/l",
      },
      {
        id: 38,
        name: "Fuel Consumption Cost Calculator",
        type: "calculator",
        inputs: [
          { name: "distance", unit: "km" },
          { name: "efficiency", unit: "km/l" },
          { name: "price", unit: "$/l" },
        ],
      },
    ],
  },
  {
    group: "Construction & Material Converters",
    items: [
      {
        id: 39,
        name: "Concrete Volume Calculator",
        type: "calculator",
        inputs: [
          { name: "length", unit: "m" },
          { name: "width", unit: "m" },
          { name: "height", unit: "m" },
        ],
      },
      {
        id: 40,
        name: "Lumber / Wood Board Feet",
        type: "calculator",
        inputs: [
          { name: "thickness", unit: "in" },
          { name: "width", unit: "in" },
          { name: "length", unit: "ft" },
        ],
      },
      {
        id: 41,
        name: "Steel Weight Calculator",
        type: "calculator",
        inputs: [
          { name: "length", unit: "m" },
          { name: "diameter", unit: "mm" },
        ],
      },
      {
        id: 42,
        name: "Tile & Flooring Calculator",
        type: "calculator",
        inputs: [
          { name: "area", unit: "m²" },
          { name: "tile_size", unit: "m²" },
        ],
      },
      {
        id: 43,
        name: "Paint Coverage Calculator",
        type: "calculator",
        inputs: [
          { name: "area", unit: "m²" },
          { name: "coverage", unit: "m²/L" },
        ],
      },
    ],
  },
  {
    group: "Health, Fitness & Nutrition",
    items: [
      {
        id: 44,
        name: "BMI Calculator",
        type: "calculator",
        inputs: [
          { name: "weight", unit: "kg" },
          { name: "height", unit: "m" },
        ],
      },
      {
        id: 45,
        name: "Body Fat Calculator",
        type: "calculator",
        inputs: [
          { name: "age", unit: "" },
          { name: "gender", unit: "" },
          { name: "weight", unit: "kg" },
          { name: "height", unit: "cm" },
        ],
      },
      {
        id: 46,
        name: "Calorie Burn Calculator",
        type: "calculator",
        inputs: [
          { name: "activity", unit: "" },
          { name: "duration", unit: "min" },
          { name: "weight", unit: "kg" },
        ],
      },
      {
        id: 47,
        name: "Pace / Running Speed Converter",
        type: "unit",
        units: ["min/km", "min/mi", "km/h", "mph"],
        base: "km/h",
      },
      {
        id: 48,
        name: "Water Intake Calculator",
        type: "calculator",
        inputs: [
          { name: "weight", unit: "kg" },
          { name: "activity_level", unit: "" },
        ],
      },
    ],
  },
  {
    group: "Cooking & Food Converters",
    items: [
      {
        id: 49,
        name: "Cooking Volume",
        type: "unit",
        units: ["cup", "tbsp", "tsp", "ml", "L"],
        base: "ml",
      },
      {
        id: 50,
        name: "Cooking Weight",
        type: "unit",
        units: ["g", "oz", "lb"],
        base: "g",
      },
      {
        id: 51,
        name: "Ingredient-Specific Converter",
        type: "calculator",
        inputs: [
          { name: "ingredient", unit: "" },
          { name: "amount", unit: "" },
          { name: "from", unit: "" },
          { name: "to", unit: "" },
        ],
      },
      {
        id: 52,
        name: "Oven Temperature",
        type: "unit",
        units: ["°C", "°F", "Gas Mark"],
        base: "°C",
      },
    ],
  },
  {
    group: "Transport & Automotive Converters",
    items: [
      {
        id: 53,
        name: "Mileage / Distance Calculator",
        type: "calculator",
        inputs: [
          { name: "fuel", unit: "L" },
          { name: "efficiency", unit: "km/l" },
        ],
      },
      {
        id: 54,
        name: "Tire Size Converter",
        type: "calculator",
        inputs: [
          { name: "width", unit: "mm" },
          { name: "aspect", unit: "%" },
          { name: "rim", unit: "in" },
        ],
      },
      {
        id: 55,
        name: "Engine Power",
        type: "unit",
        units: ["HP", "kW"],
        base: "kW",
      },
      {
        id: 56,
        name: "Fuel Economy Cost",
        type: "calculator",
        inputs: [
          { name: "distance", unit: "km" },
          { name: "efficiency", unit: "km/l" },
          { name: "price", unit: "$/l" },
        ],
      },
    ],
  },
  {
    group: "Physics & Chemistry Converters",
    items: [
      {
        id: 57,
        name: "Molar Mass Calculator",
        type: "calculator",
        inputs: [{ name: "formula", unit: "" }],
      },
      {
        id: 58,
        name: "Concentration",
        type: "unit",
        units: ["ppm", "%", "mol/L"],
        base: "mol/L",
      },
      {
        id: 59,
        name: "Radiation Units",
        type: "unit",
        units: ["Gy", "Sv"],
        base: "Gy",
      },
      {
        id: 60,
        name: "Pressure Drop",
        type: "calculator",
        inputs: [
          { name: "flow", unit: "m³/s" },
          { name: "length", unit: "m" },
          { name: "diameter", unit: "m" },
        ],
      },
    ],
  },
  {
    group: "Date, Time & Planning Tools",
    items: [
      {
        id: 61,
        name: "Age Calculator",
        type: "calculator",
        inputs: [{ name: "birthdate", unit: "YYYY-MM-DD" }],
      },
      {
        id: 62,
        name: "Date Difference Calculator",
        type: "calculator",
        inputs: [
          { name: "date1", unit: "YYYY-MM-DD" },
          { name: "date2", unit: "YYYY-MM-DD" },
        ],
      },
      {
        id: 63,
        name: "Time Zone Converter",
        type: "calculator",
        inputs: [
          { name: "time", unit: "HH:MM" },
          { name: "from_tz", unit: "" },
          { name: "to_tz", unit: "" },
        ],
      },
      {
        id: 64,
        name: "Work Hour Calculator",
        type: "calculator",
        inputs: [
          { name: "hours_per_day", unit: "" },
          { name: "days", unit: "" },
        ],
      },
      {
        id: 65,
        name: "Countdown Calculator",
        type: "calculator",
        inputs: [{ name: "target_date", unit: "YYYY-MM-DD" }],
      },
    ],
  },
  {
    group: "Miscellaneous Converters",
    items: [
      {
        id: 66,
        name: "Shoe Size Converter",
        type: "unit",
        units: ["US", "EU", "UK", "Asia"],
        base: "US",
      },
      {
        id: 67,
        name: "Clothing Size Converter",
        type: "unit",
        units: ["US", "EU", "UK"],
        base: "US",
      },
      {
        id: 68,
        name: "Number System Converter",
        type: "calculator",
        inputs: [
          { name: "number", unit: "" },
          { name: "from_base", unit: "" },
          { name: "to_base", unit: "" },
        ],
      },
      {
        id: 69,
        name: "Text Case Converter",
        type: "calculator",
        inputs: [
          { name: "text", unit: "" },
          { name: "case", unit: "upper/lower/title" },
        ],
      },
      {
        id: 70,
        name: "Roman Numeral Converter",
        type: "calculator",
        inputs: [{ name: "number", unit: "" }],
      },
    ],
  },
];
